### PR TITLE
Ashara branch

### PR DESCRIPTION
**Pull request by Amartinez2075**
Completed back end for project.

### CODE REVIEW

**Comment by Amartinez2075** [comment]
I don't know why my GitHub is slow, but this is just the code from the employee tracker assignment put here.

**Review by Afang911 — APPROVED** [review]
Looks good

**Review by Afang911 — APPROVED** [review]
Looks good

**Review by Afang911 — APPROVED** [review]
Looks good

**Review by Afang911 — APPROVED** [review]
Looks good

**Pull request merged**
